name: "Block Workflows Folder"

on:
  pull_request:
    paths:
      - '.github/workflows/**'

jobs:
  fail-workflows:
    if: github.actor != ''
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Post Custom Error Message
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "🛑 **CUSTOM ERROR:** Only the repository owner can modify GitHub workflow automation files."
            })
      - name: Force Build Failure
        run: exit 1
